plugins:
  - rubocop-minitest
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake

AllCops:
  TargetRailsVersion: 7.2
  TargetRubyVersion: 3.2
  NewCops: enable
  DisplayStyleGuide: true
  ExtraDetails: true
  Exclude:
    - .git/**/*
    - gemfiles/**/*
    - node_modules/**/*
    - test/generators/tmp/**/*
    - tmp/**/*
    - vendor/**/*

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Max: 39.86

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'Rakefile'
    - 'test/**/*'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Max: 14
  Exclude:
    - 'test/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'test/**/*'

Rails/RakeEnvironment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
