require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'vendor/bundle/**/*'
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Max: 34.26 # TODO: Lower to 15

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'Rakefile'
    - 'test/**/*'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Max: 7 # TODO: Lower to 6

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 14
  Exclude:
    - 'test/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'test/**/*'

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
