AllCops:
  DisplayCopNames: true
  Exclude:
    - 'vendor/bundle/**/*'
  TargetRubyVersion: 2.2

Metrics/AbcSize:
  Max: 34.26 # TODO: Lower to 15

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'Rakefile'
    - 'test/**/*'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Max: 7 # TODO: Lower to 6

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 14
  Exclude:
    - 'test/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'test/**/*'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

# TODO: Remove when targeting Ruby 2.3 because it is already enabled.
Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
