language: ruby
sudo: false
before_install:
  - gem update --system
  - gem update bundler
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
services:
  - mongodb
gemfile:
  - gemfiles/csv_7.0.gemfile
  - gemfiles/csv_8.0.gemfile
  - gemfiles/csv_9.0.gemfile
  - gemfiles/csv_10.0.gemfile
  - gemfiles/csv_11.0.gemfile
