language: ruby
sudo: false
before_install:
  - gem install bundler -v '~> 1.12'
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.5
  - 2.3.1
services:
  - mongodb
gemfile:
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
