language: ruby
rvm:
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
services:
  - mongodb
gemfile:
  - gemfiles/csv_15.0.gemfile
  - gemfiles/csv_16.0.gemfile
  - gemfiles/mongoid_6.0.gemfile
  - gemfiles/mongoid_7.0.gemfile
