language: ruby
sudo: false
before_install:
  - gem update --system
  - gem update bundler
rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0
services:
  - mongodb
gemfile:
  - gemfiles/csv_7.0.gemfile
  - gemfiles/csv_8.0.gemfile
  - gemfiles/csv_9.0.gemfile
  - gemfiles/csv_10.0.gemfile
  - gemfiles/csv_11.0.gemfile
  - gemfiles/csv_12.0.gemfile
