language: ruby
sudo: false
before_install:
  - gem install bundler -v '~> 1.11'
rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
services:
  - mongodb
gemfile:
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
