os: linux
dist: focal
language: ruby

rvm:
  - 2.4.10
  - 2.5.9
  - 2.6.7
  - 2.7.3
  - 3.0.1
  - ruby-head

services:
  - mongodb

gemfile:
  - gemfiles/csv_15.0.gemfile
  - gemfiles/csv_16.0.gemfile
  - gemfiles/csv_17.0.gemfile
  - gemfiles/csv_18.0.gemfile
  - gemfiles/csv_edge.gemfile
  - gemfiles/mongoid_6.0.gemfile
  - gemfiles/mongoid_7.0.gemfile
  - gemfiles/mongoid_edge.gemfile

cache:
  bundler: true

jobs:
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/csv_edge.gemfile
    - gemfile: gemfiles/mongoid_edge.gemfile
  include:
    - rvm: 2.4.10
      gemfile: Gemfile
      script: bundle exec rake rubocop
      name: RuboCop
  exclude:
    - rvm: 3.0.1
      gemfile: gemfiles/csv_15.0.gemfile
    - rvm: 3.0.1
      gemfile: gemfiles/csv_16.0.gemfile
    - rvm: 3.0.1
      gemfile: gemfiles/mongoid_6.0.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/csv_15.0.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/csv_16.0.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/mongoid_6.0.gemfile
  fast_finish: true

script: bundle exec rake test:ruby
